const subjects = [
  { name: "AGRICULTURAL SCIENCE", cat: "science" },
  { name: "ANIMAL HUSBANDRY (ALT A)", cat: "science" },
  { name: "ANIMAL HUSBANDRY (ALT B)", cat: "science" },
  { name: "APPLIED ELECTRICITY", cat: "technical" },
  { name: "AUTO BODY REPAIRS AND SPRAY PAINTING", cat: "technical" },
  { name: "AUTO ELECTRICAL WORK", cat: "technical" },
  { name: "AUTO MECHANICAL WORK", cat: "technical" },
  { name: "AUTO MECHANICS", cat: "technical" },
  { name: "AUTO PARTS MERCHANDISING", cat: "commercial" },
  { name: "BASKETRY", cat: "arts" },
  { name: "BIOLOGY", cat: "science" },
  { name: "BLOCKLAYING BRICKLAYING AND CONCRETING", cat: "technical" },
  { name: "BOOK KEEPING", cat: "commercial" },
  { name: "BUILDING CONSTRUCTION", cat: "technical" },
  { name: "BUSINESS MANAGEMENT", cat: "commercial" },
  { name: "CAPENTRY AND JOINERY", cat: "technical" },
  { name: "CATERING CRAFT PRACTICE", cat: "technical" },
  { name: "CERAMICS", cat: "arts" },
  { name: "CHEMISTRY", cat: "science" },
  { name: "CHRISTIAN RELIGIOUS STUDIES (NEW)", cat: "arts" },
  { name: "CIVIC EDUCATION", cat: "arts" },
  { name: "CLERICAL OFFICE DUTIES", cat: "commercial" },
  { name: "CLOTHING AND TEXTILES", cat: "arts" },
  { name: "COMMERCE", cat: "commercial" },
  { name: "COMPUTER STUDIES", cat: "technical" },
  { name: "COSMETOLOGY", cat: "technical" },
  { name: "CROP HUSBANDRY AND HORTICULTURE", cat: "science" },
  { name: "DATA PROCESSING", cat: "commercial" },
  { name: "DYEING & BLEACHING", cat: "arts" },
  { name: "ECONOMICS", cat: "commercial" },
  { name: "EDO", cat: "arts" },
  { name: "EFIK", cat: "arts" },
  { name: "ELECTRICAL INSTALLATION AND MAINTENANCE WORK", cat: "technical" },
  { name: "ELECTRONICS OR BASIC ELECTRONICS", cat: "technical" },
  { name: "ENGLISH LANGUAGE", cat: "arts" },
  { name: "FINANCIAL ACCOUNTING", cat: "commercial" },
  { name: "FINANCIAL ACCOUNTS", cat: "commercial" },
  { name: "FISHERIES (ALT A)", cat: "science" },
  { name: "FISHERIES (ALT B)", cat: "science" },
  { name: "FOODS AND NUTRITION", cat: "technical" },
  { name: "FORESTRY", cat: "science" },
  { name: "FRENCH", cat: "arts" },
  { name: "FURNITURE MAKING", cat: "technical" },
  { name: "FURTHER MATHEMATICS OR MATHEMATICS (ELECTIVE)", cat: "science" },
  { name: "GARMENT MAKING", cat: "technical" },
  { name: "GENERAL AGRICULTURE", cat: "science" },
  { name: "GENERAL KNOWLEDGE IN ART", cat: "arts" },
  { name: "GENERAL MATHEMATICS OR MATHEMATICS (CORE)", cat: "science" },
  { name: "GEOGRAPHY", cat: "science" },
  { name: "GHANAIAN LANGUAGES", cat: "arts" },
  { name: "GOVERNMENT", cat: "arts" },
  { name: "GRAPHIC DESIGN", cat: "arts" },
  { name: "GSM PHONES MAINTENANCE AND REPAIRS", cat: "technical" },
  { name: "HAUSA", cat: "arts" },
  { name: "HEALTH EDUCATION OR HEALTH SCIENCE", cat: "science" },
  { name: "HISTORY", cat: "arts" },
  { name: "HOME MANAGEMENT", cat: "arts" },
  { name: "IBIBIO", cat: "arts" },
  { name: "IGBO", cat: "arts" },
  { name: "INFORMATION AND COMMUNICATION TECHNOLOGY (CORE)", cat: "technical" },
  { name: "INFORMATION AND COMMUNICATION TECHNOLOGY (ELECTIVE)", cat: "technical" },
  { name: "INSURANCE", cat: "commercial" },
  { name: "INTEGRATED SCIENCE", cat: "science" },
  { name: "ISLAMIC RELIGIOUS STUDIES", cat: "arts" },
  { name: "JEWELLERY", cat: "arts" },
  { name: "LEATHER GOODS", cat: "arts" },
  { name: "LEATHERWORK", cat: "arts" },
  { name: "LITERATURE IN ENGLISH", cat: "arts" },
  { name: "MACHINE WOODWORKING", cat: "technical" },
  { name: "MARKETING", cat: "commercial" },
  { name: "METALWORK", cat: "technical" },
  { name: "MINING", cat: "science" },
  { name: "MUSIC", cat: "arts" },
  { name: "OFFICE PRACTICE", cat: "commercial" },
  { name: "PAINTING AND DECORATING", cat: "technical" },
  { name: "PHOTOGRAPHY", cat: "arts" },
  { name: "PHYSICAL EDUCATION", cat: "science" },
  { name: "PHYSICS", cat: "science" },
  { name: "PICTURE MAKING", cat: "arts" },
  { name: "PLUMBING AND PIPE FITTING", cat: "technical" },
  { name: "PRINCIPLES OF COST ACCOUNTING", cat: "commercial" },
  { name: "PRINTING CRAFT PRACTICE", cat: "technical" },
  { name: "RADIO TELEVISION AND ELECTRONICS WORKS", cat: "technical" },
  { name: "REFRIGERATION AND AIR CONDITIONING", cat: "technical" },
  { name: "SALESMANSHIP", cat: "commercial" },
  { name: "SCULPTURE", cat: "arts" },
  { name: "SHORTHAND", cat: "commercial" },
  { name: "SOCIAL STUDIES (NEW)", cat: "arts" },
  { name: "STORE KEEPING", cat: "commercial" },
  { name: "STORE MANAGEMENT", cat: "commercial" },
  { name: "TECHNICAL DRAWING", cat: "technical" },
  { name: "TEXTILES", cat: "arts" },
  { name: "TOURISM", cat: "commercial" },
  { name: "TYPEWRITING", cat: "commercial" },
  { name: "UPHOLSTERY", cat: "technical" },
  { name: "VISUAL ART", cat: "arts" },
  { name: "WELDING AND FABRICATION ENGINEERING CRAFT PRACTICE", cat: "technical" },
  { name: "WEST AFRICAN TRADITIONAL RELIGION", cat: "arts" },
  { name: "WOODWORK", cat: "technical" },
  { name: "ARABIC", cat: "arts" },
  { name: "YORUBA", cat: "arts" }
];

const categories = {
  science: [],
  commercial: [],
  arts: [],
  technical: []
};

subjects.forEach(s => {
  const id = s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  categories[s.cat].push({ id, name: s.name, image: `https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=400&q=80` });
});

console.log(JSON.stringify(categories, null, 2));
