const currentSubjects = {
  science: [
    { id: 'biology', name: 'Biology', image: '/subjects/biology_v2.png' },
    { id: 'chemistry', name: 'Chemistry', image: '/subjects/chemistry_v2.png' },
    { id: 'physics', name: 'Physics', image: '/subjects/physics_v2.png' },
    { id: 'mathematics', name: 'Mathematics', image: '/subjects/mathematics_v2.png' },
    { id: 'english', name: 'English Language', image: '/subjects/english_v2.png' },
    { id: 'literature', name: 'Literature in English', image: '/subjects/literature_v2.png' },
    { id: 'agric-science', name: 'Agricultural Science', image: '/subjects/agric_v2.png' },
    { id: 'further-maths', name: 'Further Mathematics', image: '/subjects/further_maths_v2.png' },
    { id: 'computer-science', name: 'Computer Science', image: '/subjects/computer_science_v2.png' },
    { id: 'technical-drawing', name: 'Technical Drawing', image: 'https://images.unsplash.com/photo-1503387762-592dea58ef21?auto=format&fit=crop&w=400&q=80' },
    { id: 'geography', name: 'Geography', image: '/subjects/geography_v2.png' },
    { id: 'food-nutrition', name: 'Food & Nutrition', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80' },
  ],
  commercial: [
    { id: 'economics', name: 'Economics', image: '/subjects/economics_v2.png' },
    { id: 'commerce', name: 'Commerce', image: '/subjects/commerce_v2.png' },
    { id: 'accounting', name: 'Accounting', image: '/subjects/accounting_v2.png' },
  ],
  arts: [
    { id: 'government', name: 'Government', image: '/subjects/government_v2.png' },
    { id: 'history', name: 'History', image: '/subjects/history_v2.png' },
    { id: 'crs', name: 'Christian Religious Studies (CRS)', image: 'https://images.unsplash.com/photo-1510480683064-1c6bd2069502?auto=format&fit=crop&w=400&q=80' },
  ],
  technical: [
    { id: 'basic-electronics', name: 'Basic Electronics', image: 'https://images.unsplash.com/photo-1517420812314-8b17179f59f9?auto=format&fit=crop&w=400&q=80' },
    { id: 'building-construction', name: 'Building Construction', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80' },
    { id: 'auto-mechanics', name: 'Auto Mechanics', image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=400&q=80' },
    { id: 'woodwork', name: 'Woodwork', image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=400&q=80' },
    { id: 'metalwork', name: 'Metalwork', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5f669741?auto=format&fit=crop&w=400&q=80' },
    { id: 'electrical-installation', name: 'Electrical Installation', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80' },
    { id: 'welding-fabrication', name: 'Welding & Fabrication', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=400&q=80' },
    { id: 'computer-craft', name: 'Computer Craft Studies', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=400&q=80' },
  ],
  junior: [
    { id: 'basic-science', name: 'Basic Science', image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=400&q=80' },
    { id: 'basic-tech', name: 'Basic Technology', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=400&q=80' },
    { id: 'business-studies', name: 'Business Studies', image: 'https://images.unsplash.com/photo-1454165833767-027ffea7025c?auto=format&fit=crop&w=400&q=80' },
    { id: 'social-studies', name: 'Social Studies', image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=400&q=80' },
    { id: 'home-economics', name: 'Home Economics', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=400&q=80' },
    { id: 'cca', name: 'Cultural & Creative Arts', image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=400&q=80' },
    { id: 'phe', name: 'Physical & Health Education', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=400&q=80' },
    { id: 'computer-studies', name: 'Computer Studies', image: '/subjects/computer_science_v2.png' },
    { id: 'mathematics', name: 'Mathematics', image: '/subjects/mathematics_v2.png' },
    { id: 'english', name: 'English Language', image: '/subjects/english_v2.png' },
    { id: 'mathematics-junior', name: 'Mathematics (Junior)', image: '/subjects/mathematics_v2.png' },
    { id: 'english-junior', name: 'English (Junior)', image: '/subjects/english_v2.png' },
  ]
};

const newSubjects = [
  { name: "AGRICULTURAL SCIENCE", cat: "science" },
  { name: "ANIMAL HUSBANDRY (ALT A)", cat: "science" },
  { name: "ANIMAL HUSBANDRY (ALT B)", cat: "science" },
  { name: "APPLIED ELECTRICITY", cat: "technical" },
  { name: "AUTO BODY REPAIRS AND SPRAY PAINTING", cat: "technical" },
  { name: "AUTO ELECTRICAL WORK", cat: "technical" },
  { name: "AUTO MECHANICAL WORK", cat: "technical" },
  { name: "AUTO MECHANICS", cat: "technical" },
  { name: "AUTO PARTS MERCHANDISING", cat: "commercial" },
  { name: "BASKETRY", cat: "arts" },
  { name: "BIOLOGY", cat: "science" },
  { name: "BLOCKLAYING BRICKLAYING AND CONCRETING", cat: "technical" },
  { name: "BOOK KEEPING", cat: "commercial" },
  { name: "BUILDING CONSTRUCTION", cat: "technical" },
  { name: "BUSINESS MANAGEMENT", cat: "commercial" },
  { name: "CAPENTRY AND JOINERY", cat: "technical" },
  { name: "CATERING CRAFT PRACTICE", cat: "technical" },
  { name: "CERAMICS", cat: "arts" },
  { name: "CHEMISTRY", cat: "science" },
  { name: "CHRISTIAN RELIGIOUS STUDIES (NEW)", cat: "arts" },
  { name: "CIVIC EDUCATION", cat: "arts" },
  { name: "CLERICAL OFFICE DUTIES", cat: "commercial" },
  { name: "CLOTHING AND TEXTILES", cat: "arts" },
  { name: "COMMERCE", cat: "commercial" },
  { name: "COMPUTER STUDIES", cat: "technical" },
  { name: "COSMETOLOGY", cat: "technical" },
  { name: "CROP HUSBANDRY AND HORTICULTURE", cat: "science" },
  { name: "DATA PROCESSING", cat: "commercial" },
  { name: "DYEING & BLEACHING", cat: "arts" },
  { name: "ECONOMICS", cat: "commercial" },
  { name: "EDO", cat: "arts" },
  { name: "EFIK", cat: "arts" },
  { name: "ELECTRICAL INSTALLATION AND MAINTENANCE WORK", cat: "technical" },
  { name: "ELECTRONICS OR BASIC ELECTRONICS", cat: "technical" },
  { name: "ENGLISH LANGUAGE", cat: "arts" },
  { name: "FINANCIAL ACCOUNTING", cat: "commercial" },
  { name: "FINANCIAL ACCOUNTS", cat: "commercial" },
  { name: "FISHERIES (ALT A)", cat: "science" },
  { name: "FISHERIES (ALT B)", cat: "science" },
  { name: "FOODS AND NUTRITION", cat: "technical" },
  { name: "FORESTRY", cat: "science" },
  { name: "FRENCH", cat: "arts" },
  { name: "FURNITURE MAKING", cat: "technical" },
  { name: "FURTHER MATHEMATICS OR MATHEMATICS (ELECTIVE)", cat: "science" },
  { name: "GARMENT MAKING", cat: "technical" },
  { name: "GENERAL AGRICULTURE", cat: "science" },
  { name: "GENERAL KNOWLEDGE IN ART", cat: "arts" },
  { name: "GENERAL MATHEMATICS OR MATHEMATICS (CORE)", cat: "science" },
  { name: "GEOGRAPHY", cat: "science" },
  { name: "GHANAIAN LANGUAGES", cat: "arts" },
  { name: "GOVERNMENT", cat: "arts" },
  { name: "GRAPHIC DESIGN", cat: "arts" },
  { name: "GSM PHONES MAINTENANCE AND REPAIRS", cat: "technical" },
  { name: "HAUSA", cat: "arts" },
  { name: "HEALTH EDUCATION OR HEALTH SCIENCE", cat: "science" },
  { name: "HISTORY", cat: "arts" },
  { name: "HOME MANAGEMENT", cat: "arts" },
  { name: "IBIBIO", cat: "arts" },
  { name: "IGBO", cat: "arts" },
  { name: "INFORMATION AND COMMUNICATION TECHNOLOGY (CORE)", cat: "technical" },
  { name: "INFORMATION AND COMMUNICATION TECHNOLOGY (ELECTIVE)", cat: "technical" },
  { name: "INSURANCE", cat: "commercial" },
  { name: "INTEGRATED SCIENCE", cat: "science" },
  { name: "ISLAMIC RELIGIOUS STUDIES", cat: "arts" },
  { name: "JEWELLERY", cat: "arts" },
  { name: "LEATHER GOODS", cat: "arts" },
  { name: "LEATHERWORK", cat: "arts" },
  { name: "LITERATURE IN ENGLISH", cat: "arts" },
  { name: "MACHINE WOODWORKING", cat: "technical" },
  { name: "MARKETING", cat: "commercial" },
  { name: "METALWORK", cat: "technical" },
  { name: "MINING", cat: "science" },
  { name: "MUSIC", cat: "arts" },
  { name: "OFFICE PRACTICE", cat: "commercial" },
  { name: "PAINTING AND DECORATING", cat: "technical" },
  { name: "PHOTOGRAPHY", cat: "arts" },
  { name: "PHYSICAL EDUCATION", cat: "science" },
  { name: "PHYSICS", cat: "science" },
  { name: "PICTURE MAKING", cat: "arts" },
  { name: "PLUMBING AND PIPE FITTING", cat: "technical" },
  { name: "PRINCIPLES OF COST ACCOUNTING", cat: "commercial" },
  { name: "PRINTING CRAFT PRACTICE", cat: "technical" },
  { name: "RADIO TELEVISION AND ELECTRONICS WORKS", cat: "technical" },
  { name: "REFRIGERATION AND AIR CONDITIONING", cat: "technical" },
  { name: "SALESMANSHIP", cat: "commercial" },
  { name: "SCULPTURE", cat: "arts" },
  { name: "SHORTHAND", cat: "commercial" },
  { name: "SOCIAL STUDIES (NEW)", cat: "arts" },
  { name: "STORE KEEPING", cat: "commercial" },
  { name: "STORE MANAGEMENT", cat: "commercial" },
  { name: "TECHNICAL DRAWING", cat: "technical" },
  { name: "TEXTILES", cat: "arts" },
  { name: "TOURISM", cat: "commercial" },
  { name: "TYPEWRITING", cat: "commercial" },
  { name: "UPHOLSTERY", cat: "technical" },
  { name: "VISUAL ART", cat: "arts" },
  { name: "WELDING AND FABRICATION ENGINEERING CRAFT PRACTICE", cat: "technical" },
  { name: "WEST AFRICAN TRADITIONAL RELIGION", cat: "arts" },
  { name: "WOODWORK", cat: "technical" },
  { name: "ARABIC", cat: "arts" },
  { name: "YORUBA", cat: "arts" }
];

const mergedSubjects = { ...currentSubjects };

newSubjects.forEach(s => {
  const id = s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  // Check if already exists in any category
  const exists = Object.values(mergedSubjects).some(catList => catList.some(sub => sub.id === id));
  if (!exists) {
    mergedSubjects[s.cat].push({ 
      id, 
      name: s.name, 
      image: `https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=400&q=80` 
    });
  }
});

console.log(JSON.stringify(mergedSubjects, null, 2));
